# +----------------------------------------------------------------------------+ #
# |                       CordCraft Plugin Configuration                       | #
# |                                                                            | #
# |                                Source Code :                               | #
# |                    https://github.com/xzefir/CordCraft-bot                 | #
# |                                                                            | #
# |                                 Update at :                                | #
# |              https://www.spigotmc.org/resources/cordcraft.91261/           | #
# +----------------------------------------------------------------------------+ #

# 1 - config-version : DO NOT TOUCH, IT WILL BREAK THE PLUGIN
# 2 - bot-enabeld : Enable or not the plugin (Default : true)
# 3 - port : Set the port of your Server, same as your port set in your server.properties (Default : 25599)
# 4 - guild-id : Set your Discord Guild ID (Right click on your server icon then Copy ID)
# 5 - secret-token : Your secret Token, to secure the connexion between the CordCraft Bot and the Plugin
# It will be automatically generated on Plugin Startup
config-version: 3

bot-enabeld: true

port: 25599

guild-id: 0

secret-token:
